
export const airports = [
  { name: 'Copenhagen Airport', code: 'CPH', country: '🇩🇰 Denmark' },
  { name: 'Paris Charles de Gaulle Airport', code: 'CDG', country: '🇫🇷 France' },
  { name: 'London Heathrow Airport', code: 'LHR', country: '🇬🇧 United Kingdom' },
  { name: 'Leonardo da Vinci International Airport', code: 'FCO', country: '🇮🇹 Italy' },
  { name: 'Madrid-Barajas Airport', code: 'MAD', country: '🇪🇸 Spain' },
  { name: 'Amsterdam Airport Schiphol', code: 'AMS', country: '🇳🇱 Netherlands' },
  { name: 'Frankfurt Airport', code: 'FRA', country: '🇩🇪 Germany' },
  { name: 'Sydney Airport', code: 'SYD', country: '🇦🇺 Australia' },
  { name: 'Changi Airport', code: 'SIN', country: '🇸🇬 Singapore' },
  { name: 'Los Angeles International Airport', code: 'LAX', country: '🇺🇸 United States' },
  { name: 'Zurich Airport', code: 'ZRH', country: '🇨🇭 Switzerland' },
  { name: 'Oslo Airport', code: 'OSL', country: '🇳🇴 Norway' },
  { name: 'Stockholm Arlanda Airport', code: 'ARN', country: '🇸🇪 Sweden' },
  { name: 'Toronto Pearson International Airport', code: 'YYZ', country: '🇨🇦 Canada' },
  { name: 'Dublin Airport', code: 'DUB', country: '🇮🇪 Ireland' },
  { name: 'Tokyo Haneda Airport', code: 'HND', country: '🇯🇵 Japan' },
  { name: 'Incheon International Airport', code: 'ICN', country: '🇰🇷 South Korea' },
  { name: 'Hong Kong International Airport', code: 'HKG', country: '🇭🇰 Hong Kong' },
  { name: 'Taiwan Taoyuan International Airport', code: 'TPE', country: '🇹🇼 Taiwan' }
]

export const airportsNomad = [
  { code: 'KUL', name: 'Kuala Lumpur International Airport', country: '🇲🇾 Malaysia' },
  { code: 'HND', name: 'Tokyo International Airport', country: '🇯🇵 Japan' },
  { code: 'ICN', name: 'Incheon International Airport', country: '🇰🇷 South Korea' },
  { code: 'PEK', name: 'Beijing Capital International Airport', country: '🇨🇳 China' },
  { code: 'BKK', name: 'Suvarnabhumi Airport', country: '🇹🇭 Thailand' },
  { code: 'SGN', name: 'Tan Son Nhat International Airport', country: '🇻🇳 Vietnam' },
  { code: 'PNH', name: 'Phnom Penh International Airport', country: '🇰🇭 Cambodia' },
  { code: 'CGK', name: 'Soekarno–Hatta International Airport', country: '🇮🇩 Indonesia' },
  { code: 'MNL', name: 'Ninoy Aquino International Airport', country: '🇵🇭 Philippines' },
  { code: 'MEX', name: 'Mexico City International Airport', country: '🇲🇽 Mexico' },
  { code: 'BOG', name: 'El Dorado International Airport', country: '🇨🇴 Colombia' },
  { code: 'LIM', name: 'Jorge Chávez International Airport', country: '🇵🇪 Peru' },
  { code: 'UIO', name: 'Mariscal Sucre International Airport', country: '🇪🇨 Ecuador' },
  { code: 'VVI', name: 'Viru Viru International Airport', country: '🇧🇴 Bolivia' },
  { code: 'GUA', name: 'La Aurora International Airport', country: '🇬🇹 Guatemala' },
  { code: 'MGA', name: 'Augusto C. Sandino International Airport', country: '🇳🇮 Nicaragua' },
  { code: 'SJO', name: 'Juan Santamaría International Airport', country: '🇨🇷 Costa Rica' },
  { code: 'PTY', name: 'Tocumen International Airport', country: '🇵🇦 Panama' },
  { code: 'DEL', name: 'Indira Gandhi International Airport', country: '🇮🇳 India' },
  { code: 'KTM', name: 'Tribhuvan International Airport', country: '🇳🇵 Nepal' },
  { code: 'CMB', name: 'Bandaranaike International Airport', country: '🇱🇰 Sri Lanka' },
  { code: 'CMN', name: 'Mohammed V International Airport', country: '🇲🇦 Morocco' },
  { code: 'CAI', name: 'Cairo International Airport', country: '🇪🇬 Egypt' },
  { code: 'IST', name: 'Istanbul Airport', country: '🇹🇷 Turkey' }
]
